<a href="https://colab.research.google.com/github/AnugyaPandey/-Lenght-width-of-flowers-using-ML-PYTHON/blob/main/Anugya_Sanjay_Pandey.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Here I have imported some libraries:


In [1]:
import pandas as pd
import numpy as  np


Exploring the data:

In [3]:
from sklearn.datasets import load_iris
iris_datasets=load_iris()


The iris object contains keys and values:


In [4]:
print("keys of iris_dataset:\n{}".format(iris_datasets.keys()))

keys of iris_dataset:
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


The key DESCR is short description of the dataset it contians:

In [5]:
print(iris_datasets['DESCR'][:193] + "\n..")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre
..


The value of the key target_name is an array of strings contains species of flower we need to predict ie.'setosa','versicolor' & 'verginica'

In [6]:
print("target_names:{}".format(iris_datasets['target_names']))

target_names:['setosa' 'versicolor' 'virginica']


The value of key feature_names is a list of strings,it contains:

In [7]:
print("feature_names: \n{}".format(iris_datasets['feature_names']))

feature_names: 
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


The type of data contains:

In [8]:
print("type of data: {}".format(type(iris_datasets['data'])))

type of data: <class 'numpy.ndarray'>


Shape of data contains:

In [ ]:
print("Shape of data: {}".format(iris_datasets['data'].shape))

Shape of data: (150, 4)


feature values of first five samples are:

In [9]:
print("first five columns of data are:\n{}".format(iris_datasets['data'][:5]))

first five columns of data are:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


Type of target contains:

In [11]:
print("Type of target: {}".format(type(iris_datasets['target'])))

Type of target: <class 'numpy.ndarray'>


Shape of target contains:

In [12]:
print("Shape of target: {}".format(iris_datasets['target'].shape))

Shape of target: (150,)


The key target explores the values & encode the integer from 0 to 2 :

In [15]:
print("target: {}".format(iris_datasets['target']))

target: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


Training & Testing data:

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(
iris_datasets['data'], iris_datasets['target'], random_state=0)

The output of train_test_split function is:

In [18]:
print("X_train shape: {}".format(X_train.shape))
print("y_train shape: {}".format(y_train.shape))
print("X_test shape: {}".format(X_test.shape))
print("y_test shape:{}".format(y_test.shape))

X_train shape: (112, 4)
y_train shape: (112,)
X_test shape: (38, 4)
y_test shape:(38,)


K-nearest neighbor Machine learning model:

In [19]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

Algorithm to build the model from training data:

In [20]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

Making Predictions:

In [21]:
X_new = np.array([[5, 2.9, 1, 0.2]])
print("X_new.shape: {}".format(X_new.shape))

X_new.shape: (1, 4)


Making prediction for particular point:

In [22]:
prediction = knn.predict(X_new)
print("Prediction: {}".format(prediction))
print("Predicted target name: {}".format(
iris_datasets['target_names'][prediction]))

Prediction: [0]
Predicted target name: ['setosa']


Evaluating the Model:

In [23]:
y_pred = knn.predict(X_test)
print("Test set predictions:\n {}".format(y_pred))

Test set predictions:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [24]:
print("Test set score: {}".format(np.mean(y_pred == y_test)))

Test set score: 0.9736842105263158
